version: '3.9'

services:
#  app:
#    build: .
##      context: .
#    container_name: django_container
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/django
#    ports:
#     - 8000:8000
#    image: app:django
#    depends_on:
#      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
#      POSTGRES_DB: Data_Hive
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1Thesaint
    expose:
      - 5432
#    ports:
#      - 5432:5432
    restart: always
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080